In [35]:
import numpy as np
import pandas as pd
from tensorflow import keras
import matplotlib as mpl
import matplotlib.pyplot as plt
import os
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

In [36]:
model = keras.models.load_model("../Saved Data/Model")
X_test = np.load('../Saved Data/X_test.npy')
y_test = np.load('../Saved Data/y_test.npy')

In [37]:
y_pred = np.argmax(model.predict(X_test), axis=1)
accuracy_score = accuracy_score(y_test, y_pred)
precision_score = precision_score(y_test, y_pred, average='macro')
recall_score = recall_score(y_test, y_pred, average='macro')
f1_score = f1_score(y_test, y_pred, average='macro')
confusion_matrix = confusion_matrix(y_test, y_pred)
classification_report = classification_report(y_test, y_pred)

28/28 [==============================] - 0s 11ms/step


In [38]:
print(f"Classification Accuracy = {round(accuracy_score * 100, 2)}%\nPrecision = {round(precision_score * 100, 2)}%\nRecall = {round(recall_score * 100, 2)}%\nF1 Score = {round(f1_score * 100, 2)}%")

Classification Accuracy = 82.42%
Precision = 85.21%
Recall = 79.12%
F1 Score = 80.78%


In [40]:
print(confusion_matrix)

[[ 75   4   0   1   9   0   4]
 [  1  93   0   1   6   1   5]
 [  1   7  58   1  15   1   6]
 [  1   4   1 102  24   1   6]
 [  3   1   0   1 112   2   4]
 [  0   1   0   1   7  30   6]
 [  1   5   0   3  19   0 252]]
