In [26]:
import os
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from tensorflow import keras
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

In [27]:
model = keras.models.load_model("../Saved Data/Model")
X_test = np.load('../Saved Data/Test Set/X_test.npy')
y_test = np.load('../Saved Data/Test Set/y_test.npy')

In [28]:
y_pred = np.argmax(model.predict(X_test), axis=1)
np.savetxt('../Saved Data/Predicted Labels/python_model.txt', y_pred, fmt='%d')
accuracy_score = accuracy_score(y_test, y_pred)
precision_score = precision_score(y_test, y_pred, average='macro')
recall_score = recall_score(y_test, y_pred, average='macro')
f1_score = f1_score(y_test, y_pred, average='macro')
confusion_matrix = confusion_matrix(y_test, y_pred)
classification_report = classification_report(y_test, y_pred)

28/28 [==============================] - 0s 5ms/step


In [29]:
print(f"Classification Accuracy = {round(accuracy_score * 100, 2)}%\nPrecision = {round(precision_score * 100, 2)}%\nRecall = {round(recall_score * 100, 2)}%\nF1 Score = {round(f1_score * 100, 2)}%")

Classification Accuracy = 84.25%
Precision = 85.52%
Recall = 80.89%
F1 Score = 82.51%


In [30]:
print(confusion_matrix)

[[ 83   3   0   3   0   1   3]
 [  1  92   0   5   2   0   7]
 [  1   1  75   3   1   0   8]
 [  3   1   2 117   3   1  12]
 [  6   3   2  17  83   2  10]
 [  7   1   0   2   1  28   6]
 [  6   0   1  10   3   0 260]]
